### ISSUE TITLE
Searching suddenly stopped returning results

### ISSUE THREAD

**Issue by mspriggs** [westerlind/alfred-raindrop-search#29]
Using the Alfred search returns no results for any and all search terms that used to produce results in Raindrop. Chrome is default browser. Mac, Sonoma (14.1.2 (23B92))

**Comment by westerlind** [comment]
Hi @mspriggs 

It still works for me, so it does not seem to be a problem with the Raindrop service anyway.

My first guess would then be that it might be possible to resolve it by forcing a log out, which you can do by opening the Keychain Access app, search for raindrop, and remove the object that you find.
Nex time you try to search for something with the Raindrop workflow, it will guide you to log in again.

**Comment by davidisongithub** [comment]
I experience the same problem as @mspriggs mentioned.

**Comment by westerlind** [comment]
Hi

I think this has to do with the following, which I'm quoting from a mail that Raindrop sent out earlier today.

The described problem below does seem to match what you describe, and as it also sounds like it might only affect some regions, that would explain why I can't reproduce it myself.

**Greetings!**

**Since December 14th, our search feature has encountered technical difficulties due to problems with one of our hosting providers. As a result, search results, including filters and tags, may be incomplete or outdated. Rest assured, your data is safe. Only a portion of our servers are affected, and they do not store any data.**

**We are working diligently to resolve this issue as quickly as possible. Tomorrow, the search and filtering functions will be fully restored. However, restoring full-text search will take more time and is expected to be completed by the end of the week.**

**Please accept our apologies for any inconvenience this may cause.**

**Comment by mspriggs** [comment]
I saw that announcement as well. However, I did try your suggestion of deleting the object in Keychain Access and then re-authenticating. That seemed to do the trick. Thanks!
