### ISSUE TITLE
Update or maintained 

### ISSUE THREAD

**Issue by ljci** [westerlind/alfred-raindrop-search#31]
I am just curious if this repo is constantly updating or being maintained because I saw the raycast raindrop extension keeps updating. 
In addition, I define geek as one of folder name in raindrop, then I can not search it using Alfred with raindrop.io, I don’t know why. 
Also raindrop search is a little bit slow, it would be great if we could check the raycast raindrop extension and see what we can do better. 
I appreciate your answer and the raindrop workflow is great, just want it to be better

**Comment by westerlind** [comment]
Hi @ljcliu

I consider this an active project, but it's true that it isn't getting all that many updates lately.
For a while I have mostly only fixed bugs that someone finds, but I have some other plans and have done some testing for eventually adding support for caching the most basic info about all bookmarks locally so that it will be possible to select between 2 different ways of searching your bookmarks:
1. As it currenyly works, which means that the search is done serverside (at Raindrop.io) which is not the fastest it could have possibly been but makes it possible to do advanced searches, for example with full text search, so that you could find results based on something that is written on the bookmarked page rather than just in the title.
2. Searching a locally cached list of bookmarks that is updated periodically, which would mean very fast searches, but would also have some downsides, especially that it would not be able to give as good results (no full text search for example).

I can't really say when this will be done and ready to use, but it should happen eventually.

**Comment by westerlind** [comment]
About the folder that you can not search.
Do you mean that you can't find bookmarks in this folder, or does the folder itself not show up in searches?

**Comment by ljci** [comment]
Thanks for such clear comment and your workflow.

For folder search question, I mean the folder itself didn’t show up
immediately after I rename the it in raindrop but it works perfectly in my
recent renaming and searching with your workflow.

In general,  the problem is workflow have a time lag between action in
raindrop and search results of workflow.

Andreas Westerlind ***@***.***>于2024年3月26日 周二16:19写道：

**Comment by westerlind** [comment]
Ah! Good that it works now anyway then.

The bookmark folders are cached locally for a little while to make searching them faster, so that is probably the reason that changes in folder names are not showing up right away while searching with this workflow, as they are not always downloaded from the server to avaid slowing things down (the icons for folders are also cached longer than the names, so if you change the icon of a folder, that will take longer to show in the workflow)

This is the same kind of problem that would also happen if the workflow would cache the bookmarks locally to improve speed (as I explained previously), but at the moment this only happens with folders and tags (and not for very long) and not the actual bookmarks, so there is a balance between speed and acuracy here that is somewhat hard to do perfectly because everyone uses a bookmark service differently, and what is perfect for me might not be for you, but I have tried to do my best to get as good of a balance as possible for these things.
