### ISSUE TITLE
loading too slow

### ISSUE THREAD

**Issue by ljci** [westerlind/alfred-raindrop-search#34]
Hi @westerlind ,
Thanks so much for this awesome workflow, I used it very often. However, using often is also a issue because the loading bookmark is too slow. Are you still maintaining this repo? 
I just checked raycast and raindrop.io, is there anything there can help you on solving slowing loading problem?  Here is the link https://www.raycast.com/lardissone/raindrop-io

Looking forward to hearing back from you soon! Thanks again.

**Comment by westerlind** [comment]
Hi @ljci 

It's still maintained, but (if you don't take the alternative faster way of searching into account) it already does most of what I can think of for a workflow like this, so the updates are usually just bug fixes these days.

The reason that the search results are not instant is that it uses Raindrop's API to do the search, meaning that it does not do the searching locally but has to wait for Raindrop's servers to return the results of the query before it can be displayed. So because of that, it is not currently able to be faster then the Raindrop service itself at searching.

The advantages of doing it that way is that you actually search the full content of the bookmarks ("full text search"), and not just titles and possibly descriptions (at least if you are using the paid plan for Raindrop, which is needed for that feature), and that changes to the bookmarks are reflected immediately in your searches. New (or changed) bookmarks are included in the search as soon as they are added.

The disadvantage is that it might take around 1 second (at least for me) to get the results, instead of being almost instant if the workflow would instead cache info about titles, url's and maybe descriptions locally on your computer, update that cache periodically, and then do a really fast local search on that content instead of asking the servers to do the search.

I personally prefer the advantages of the current method, which is somewhat slower (but not really that slow) but gives better results, and that's the main reason why the workflow uses this method at the moment.

For me, being able to get full text search (even if it's slightly slower) as the main way of searching through my bookmarks was one of the main reasons I started to use Raindrop myself a few years ago, and why I created this workflow instead of just using some other bookmark service and someone else's workflow that didn't do full text search.

I have been looking into adding that other faster search variant that only searches cached titles and descriptions too though (I have a proof of concept of it), so that everyone can choose which method they prefer themselves, but I don't know when that will be ready.

**Comment by ljci** [comment]
> Hi @ljci
> 
> It's still maintained, but (if you don't take the alternative faster way of searching into account) it already does most of what I can think of for a workflow like this, so the updates are usually just bug fixes these days.
> 
> The reason that the search results are not instant is that it uses Raindrop's API to do the search, meaning that it does not do the searching locally but has to wait for Raindrop's servers to return the results of the query before it can be displayed. So because of that, it is not currently able to be faster then the Raindrop service itself at searching.
> 
> The advantages of doing it that way is that you actually search the full content of the bookmarks ("full text search"), and not just titles and possibly descriptions (at least if you are using the paid plan for Raindrop, which is needed for that feature), and that changes to the bookmarks are reflected immediately in your searches. New (or changed) bookmarks are included in the search as soon as they are added.
> 
> The disadvantage is that it might take around 1 second (at least for me) to get the results, instead of being almost instant if the workflow would instead cache info about titles, url's and maybe descriptions locally on your computer, update that cache periodically, and then do a really fast local search on that content instead of asking the servers to do the search.
> 
> I personally prefer the advantages of the current method, which is somewhat slower (but not really that slow) but gives better results, and that's the main reason why the workflow uses this method at the moment.
> 
> For me, being able to get full text search (even if it's slightly slower) as the main way of searching through my bookmarks was one of the main reasons I started to use Raindrop myself a few years ago, and why I created this workflow instead of just using some other bookmark service and someone else's workflow that didn't do full text search.
> 
> I have been looking into adding that other faster search variant that only searches cached titles and descriptions too though (I have a proof of concept of it), so that everyone can choose which method they prefer themselves, but I don't know when that will be ready.

Thanks for your such detailed reply. I appreciate your time and providing us such a great workflow! Have a great day
